CREATE TABLE users (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    nombre VARCHAR(255) NOT NULL,
    email VARCHAR(255) NOT NULL UNIQUE,
    password VARCHAR(255) NOT NULL,
    role VARCHAR(32) NOT NULL,
    status VARCHAR(32) NOT NULL DEFAULT 'ACTIVE',
    profesor_id BIGINT REFERENCES users(id)
);

CREATE TABLE exercises (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    nombre VARCHAR(255) NOT NULL,
    musculo VARCHAR(255) NOT NULL,
    descripcion VARCHAR(255),
    imagen_url VARCHAR(255),
    video_url VARCHAR(255),
    created_by_id BIGINT REFERENCES users(id)
);

CREATE TABLE training_plans (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    client_id BIGINT NOT NULL REFERENCES users(id),
    exercise_id BIGINT NOT NULL REFERENCES exercises(id),
    sets INTEGER,
    reps INTEGER,
    peso_sugerido DOUBLE PRECISION,
    notas_extras VARCHAR(255)
);

CREATE TABLE exercise_progress (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id BIGINT NOT NULL REFERENCES users(id),
    exercise_id BIGINT NOT NULL REFERENCES exercises(id),
    peso_usado DOUBLE PRECISION NOT NULL,
    reps_realizadas INTEGER NOT NULL,
    sets_realizados INTEGER NOT NULL,
    notas VARCHAR(255),
    fecha TIMESTAMP NOT NULL
);

CREATE INDEX idx_users_profesor_id ON users(profesor_id);
CREATE INDEX idx_training_plans_client_id ON training_plans(client_id);
CREATE INDEX idx_exercise_progress_user_id ON exercise_progress(user_id);
